name: User Admin CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: user-admin

jobs:
  lint:
    name: Análise estática
    runs-on: ubuntu-latest
    env:
          MONGO_URL: mongodb://root:root@localhost:27017/qa-mastery
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.1
          cache: "npm"
          cache-dependency-path: "user-admin/package-lock.json"
      - run: npm ci
      - run: npm run lint

  vulnerability:
    name: Teste de Vulnerabilidade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.1
          cache: "npm"
          cache-dependency-path: "user-admin/package-lock.json"
      - run: npm ci
      - run: npm audit --production

  tests:
    name: Testes de Sistema (E2E)
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.1
          cache: "npm"
          cache-dependency-path: "user-admin/package-lock.json"

      - name: Install dependencies
        working-directory: user-admin
        run: |
          npm ci
          npm install react-scripts --save-dev

      - name: Starts API server in background        
        run: |
          npm --prefix ../user-api ci
          npm --prefix ../user-api run start &
          sleep 10

      - name: Run cypress
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          working-directory: user-admin
          install-command: npm ci
        env:
          MONGO_URL: mongodb://root:root@localhost:27017/qa-mastery

      - name: Arquiva os videos e screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: artifacts
          path: |
            user-admin/cypress/screenshots/
            user-admin/cypress/videos/
          retention-days: 1
